'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Answer
    Public Property ANSID As Integer
    Public Property ANSDescription As String
    Public Property ANSStatus As Boolean
    Public Property QID As Integer
    Public Property USERID As Nullable(Of Integer)

    Public Overridable Property Question As Question
    Public Overridable Property User As User

End Class
