'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Question
    Public Property QID As Integer
    Public Property QDescription As String
    Public Property QType As String
    Public Property QAnswersNum As Integer
    Public Property LSNID As Integer
    Public Property USERID As Nullable(Of Integer)

    Public Overridable Property Answers As ICollection(Of Answer) = New HashSet(Of Answer)
    Public Overridable Property Lesson As Lesson
    Public Overridable Property User As User

End Class
