'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property STDID As Integer
    Public Property USERID As Integer
    Public Property CLASSID As Integer
    Public Property YEARID As Integer
    Public Property STDNationality As String
    Public Property STDgender As String
    Public Property STDPhone As String
    Public Property STDDateOfBirth As Nullable(Of Date)

    Public Overridable Property [Class] As [Class]
    Public Overridable Property User As User
    Public Overridable Property Year As Year
    Public Overridable Property Subjects As ICollection(Of Subject) = New HashSet(Of Subject)

End Class
