'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Subject
    Public Property SUBID As Integer
    Public Property SUBName As String
    Public Property SUBDescription As String
    Public Property SUBPicture As Byte()
    Public Property YEARID As Integer
    Public Property STDID As Nullable(Of Integer)
    Public Property USERID As Nullable(Of Integer)

    Public Overridable Property Lessons As ICollection(Of Lesson) = New HashSet(Of Lesson)
    Public Overridable Property Student As Student
    Public Overridable Property User As User
    Public Overridable Property Year As Year

End Class
