'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property USERID As Integer
    Public Property UserName As String
    Public Property USERPassword As String
    Public Property InserPre As Nullable(Of Boolean)
    Public Property DeletePre As Nullable(Of Boolean)
    Public Property UpdatePre As Nullable(Of Boolean)
    Public Property USERAdminRight As Nullable(Of Boolean)
    Public Property MangmentSubject As Nullable(Of Boolean)
    Public Property manegmentStudent As Nullable(Of Boolean)
    Public Property ManegmentClass As Nullable(Of Boolean)
    Public Property ManegmentUsers As Nullable(Of Boolean)
    Public Property PreStudent As Nullable(Of Boolean)
    Public Property ManegmentQuestions As Nullable(Of Boolean)
    Public Property ManegmentYears As Nullable(Of Boolean)

    Public Overridable Property Answers As ICollection(Of Answer) = New HashSet(Of Answer)
    Public Overridable Property Classes As ICollection(Of [Class]) = New HashSet(Of [Class])
    Public Overridable Property Lessons As ICollection(Of Lesson) = New HashSet(Of Lesson)
    Public Overridable Property Questions As ICollection(Of Question) = New HashSet(Of Question)
    Public Overridable Property Students As ICollection(Of Student) = New HashSet(Of Student)
    Public Overridable Property Subjects As ICollection(Of Subject) = New HashSet(Of Subject)
    Public Overridable Property Years As ICollection(Of Year) = New HashSet(Of Year)

End Class
