'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Year
    Public Property YEARID As Integer
    Public Property USERID As Nullable(Of Integer)
    Public Property YEAR1 As String

    Public Overridable Property Students As ICollection(Of Student) = New HashSet(Of Student)
    Public Overridable Property Subjects As ICollection(Of Subject) = New HashSet(Of Subject)
    Public Overridable Property User As User

End Class
